version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/mariadb:10.3.9-ram
      environment:
        - MYSQL_ROOT_PASSWORD: yoyo
        - MYSQL_DATABASE: sillynaut
        - MYSQL_USER: silly
        - MYSQL_PASSWORD: naut

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1G
      TERM: dumb

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-sillynaut{{ checksum "build.gradle" }}
        - v1-dependencies-sillynaut

    - run: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-sillynaut{{ checksum "build.gradle" }}

    - run: gradle check



